//*********************************************
//  This is auto generated by G4gen 0.6
//                                  author:Qian

#ifndef Verbose_hh
#define Verbose_hh

#include "G4Types.hh"
#include "G4String.hh"


extern G4int verbose;  //0, mean no output; !=0, means output user defined messages

extern G4int runID; // run ID
extern G4String gunType; //particle gun type
extern G4String gdmlFile; //gdml for detector
extern G4String evtStore; //event store type

#endif
